import {
  Controller,
  Post,
  Get,
  Body,
  Param,
  ParseIntPipe,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiParam,
  ApiCreatedResponse,
  ApiOkResponse,
} from '@nestjs/swagger';
import { AiService } from './ai.service';
import {
  SessionResponseDto,
  ProposalResponseDto,
  EventResponseDto,
  ResultStateResponseDto,
  UsageStatsResponseDto,
} from './dto/responses';
import { CreateEventDto } from './dto/create-event.dto';
import { CreateProposalsDto } from './dto/create-proposals.dto';
import { CreateSessionDto } from './dto/create-session.dto';
import { SaveChangesDto } from './dto/save-changes.dto';
import { UserToken } from '../../shared/decorators/user-token.decorator';
import { TokenDto } from '../../shared/globalInterfaces/token.dto';

@ApiTags('AI Review')
@Controller()
export class AiController {
  constructor(private readonly aiService: AiService) {}

  @Post('sessions')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Create AI review session',
    description:
      'Creates a new AI review session and logs the opening event. This is called when a user opens the AI review modal.',
  })
  @ApiCreatedResponse({
    description: 'Session created successfully',
    type: SessionResponseDto,
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - invalid input data',
  })
  @ApiBody({
    type: CreateSessionDto,
    description: 'Session creation data',
    examples: {
      example: {
        summary: 'Create session example',
        value: {
          result_id: 123,
        },
      },
    },
  })
  async createSession(
    @Body() createSessionDto: CreateSessionDto,
    @UserToken() user: TokenDto,
  ): Promise<SessionResponseDto> {
    return this.aiService.createSession(createSessionDto, user);
  }

  @Post('sessions/:sessionId/close')
  @ApiOperation({
    summary: 'Close AI review session',
    description:
      'Closes an existing AI review session and logs the closing event. This is called when a user closes the AI review modal.',
  })
  @ApiOkResponse({
    description: 'Session closed successfully',
    type: SessionResponseDto,
  })
  @ApiResponse({
    status: 404,
    description: 'Session not found',
  })
  @ApiParam({
    name: 'sessionId',
    description: 'ID of the session to close',
    type: Number,
    example: 1,
  })
  async closeSession(
    @Param('sessionId', ParseIntPipe) sessionId: number,
    @UserToken() user: TokenDto,
  ): Promise<SessionResponseDto> {
    return this.aiService.closeSession(sessionId, user);
  }

  @Post('sessions/:sessionId/proposals')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Save AI-generated proposals',
    description:
      'Saves the proposals generated by the external AI service for a specific session. These proposals will be displayed to the user in the modal.',
  })
  @ApiCreatedResponse({
    description: 'Proposals saved successfully',
    type: [ProposalResponseDto],
  })
  @ApiResponse({
    status: 404,
    description: 'Session not found',
  })
  @ApiParam({
    name: 'sessionId',
    description: 'ID of the session to save proposals for',
    type: Number,
    example: 1,
  })
  @ApiBody({
    type: CreateProposalsDto,
    description: 'Proposals data from AI service',
    examples: {
      example: {
        summary: 'Save proposals example',
        value: {
          proposals: [
            {
              field_name: 'title',
              original_text: 'Original title text',
              proposed_text: 'Improved title text',
              needs_improvement: true,
            },
            {
              field_name: 'description',
              original_text: 'Original description',
              proposed_text: 'Enhanced description',
              needs_improvement: false,
            },
          ],
        },
      },
    },
  })
  async createProposals(
    @Param('sessionId', ParseIntPipe) sessionId: number,
    @Body() createProposalsDto: CreateProposalsDto,
  ): Promise<ProposalResponseDto[]> {
    return this.aiService.createProposals(sessionId, createProposalsDto);
  }

  @Get('sessions/:sessionId/proposals')
  @ApiOperation({
    summary: 'Get AI proposals for session',
    description:
      'Retrieves all AI-generated proposals for a specific session to display them in the frontend modal.',
  })
  @ApiOkResponse({
    description: 'Proposals retrieved successfully',
    type: [ProposalResponseDto],
  })
  @ApiResponse({
    status: 404,
    description: 'Session not found',
  })
  @ApiParam({
    name: 'sessionId',
    description: 'ID of the session to get proposals for',
    type: Number,
    example: 1,
  })
  async getProposals(
    @Param('sessionId', ParseIntPipe) sessionId: number,
  ): Promise<ProposalResponseDto[]> {
    return this.aiService.getProposals(sessionId);
  }

  @Post('events')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Track AI review event',
    description:
      'Logs user interactions with the AI review interface (apply proposal, regenerate, save changes, etc.). Used for analytics and audit trails.',
  })
  @ApiCreatedResponse({
    description: 'Event logged successfully',
    type: EventResponseDto,
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - invalid event data',
  })
  @ApiBody({
    type: CreateEventDto,
    description: 'Event tracking data',
    examples: {
      example: {
        summary: 'Track apply proposal event',
        value: {
          session_id: 1,
          result_id: 123,
          user_id: 456,
          event_type: 'APPLY_PROPOSAL',
          field_name: 'title',
        },
      },
      regenerate_example: {
        summary: 'Track regenerate event',
        value: {
          session_id: 1,
          result_id: 123,
          user_id: 456,
          event_type: 'REGENERATE',
          field_name: 'description',
        },
      },
    },
  })
  async createEvent(
    @Body() createEventDto: CreateEventDto,
    @UserToken() user: TokenDto,
  ): Promise<EventResponseDto> {
    return this.aiService.createEvent(createEventDto, user);
  }

  @Post('sessions/:sessionId/save')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Save final changes to result',
    description:
      'Saves the final text chosen by the user to the actual result record. Creates audit trail entries and updates AI state tracking.',
  })
  @ApiOkResponse({
    description: 'Changes saved successfully',
  })
  @ApiResponse({
    status: 404,
    description: 'Session not found',
  })
  @ApiParam({
    name: 'sessionId',
    description: 'ID of the session to save changes for',
    type: Number,
    example: 1,
  })
  @ApiBody({
    type: SaveChangesDto,
    description: 'Final changes to save',
    examples: {
      example: {
        summary: 'Save changes example',
        value: {
          fields: [
            {
              field_name: 'title',
              new_value: 'Improved title text',
              change_reason: 'Applied AI suggestion',
              was_ai_suggested: true,
              user_feedback: 'Good suggestion',
            },
            {
              field_name: 'description',
              new_value: 'Enhanced description text',
              change_reason: 'Manual edit after AI review',
              was_ai_suggested: false,
            },
          ],
          user_id: 456,
        },
      },
    },
  })
  async saveChanges(
    @Param('sessionId', ParseIntPipe) sessionId: number,
    @Body() saveChangesDto: SaveChangesDto,
    @UserToken() user: TokenDto,
  ): Promise<void> {
    return this.aiService.saveChanges(sessionId, saveChangesDto, user);
  }

  @Get('results/:resultId/state')
  @ApiOperation({
    summary: 'Get AI suggestion state for result',
    description:
      'Returns the current AI suggestion status for each field of a result. Used to display "AI suggested" tags in the UI.',
  })
  @ApiOkResponse({
    description: 'State retrieved successfully',
    type: ResultStateResponseDto,
  })
  @ApiParam({
    name: 'resultId',
    description: 'ID of the result to get state for',
    type: Number,
    example: 123,
  })
  async getResultState(
    @Param('resultId', ParseIntPipe) resultId: number,
  ): Promise<ResultStateResponseDto> {
    return this.aiService.getResultState(resultId);
  }

  @Get('results/:resultId/stats')
  @ApiOperation({
    summary: 'Get AI review usage statistics',
    description:
      'Returns usage statistics and metrics for AI review features on a specific result (total sessions, events by type, etc.).',
  })
  @ApiOkResponse({
    description: 'Statistics retrieved successfully',
    type: UsageStatsResponseDto,
  })
  @ApiParam({
    name: 'resultId',
    description: 'ID of the result to get statistics for',
    type: Number,
    example: 123,
  })
  async getResultStats(
    @Param('resultId', ParseIntPipe) resultId: number,
  ): Promise<UsageStatsResponseDto> {
    return this.aiService.getResultStats(resultId);
  }
}
