import { Component } from '@angular/core';

@Component({
  selector: 'app-innovation-package-list',
  templateUrl: './innovation-package-list.component.html',
  styleUrls: ['./innovation-package-list.component.scss']
})
export class InnovationPackageListComponent {
  tableData = [
    { id: 1, title: 'Granny', submitter: 'CBH', status_name: 'Ibuprofen', year: 1993 },
    { id: 2, title: 'Sabra', submitter: 'TFY', status_name: 'Dentastat', year: 2011 },
    { id: 3, title: 'Annice', submitter: 'AUG', status_name: 'LBEL COULEUR LUXE AMPLIFIER XP', year: 1989 },
    { id: 4, title: 'Henry', submitter: 'POP', status_name: 'CVS Maximum Strength Boil Relief', year: 2001 },
    { id: 5, title: 'Yorgos', submitter: 'LFM', status_name: 'Neutrogena SkinClearing', year: 1999 },
    { id: 6, title: 'Kippy', submitter: 'GKN', status_name: 'Ampicillin and Sulbactam', year: 2012 },
    { id: 7, title: 'Shepherd', submitter: 'CBQ', status_name: 'Orajel Instant Pain Relief', year: 1966 },
    { id: 8, title: 'Ally', submitter: 'TKO', status_name: 'Parsnip', year: 1989 },
    { id: 9, title: 'Olwen', submitter: 'EYL', status_name: 'Clonidine Hydrochloride', year: 2010 },
    { id: 10, title: 'Carmella', submitter: 'KLN', status_name: 'Penicillin V Potassium', year: 2008 },
    { id: 11, title: 'Elysia', submitter: 'EGV', status_name: 'CD - Dior Multi-perfection Tinted Moisturizer Bronze Radiance 3 - SPF 20', year: 1999 },
    { id: 12, title: 'Tabbatha', submitter: 'JAI', status_name: 'Nystatin', year: 1988 },
    { id: 13, title: 'Farleigh', submitter: 'RBW', status_name: 'Telmisartan', year: 2008 },
    { id: 14, title: 'Lillian', submitter: 'WKB', status_name: 'DHS TAR GEL', year: 1992 },
    { id: 15, title: 'Wandis', submitter: 'KQA', status_name: 'TRAMADOL HYDROCHLORIDE', year: 2007 },
    { id: 16, title: 'Tobye', submitter: 'RSX', status_name: 'Buspirone HCl', year: 1970 },
    { id: 17, title: 'Leoline', submitter: 'TVF', status_name: 'Sunmark infants gas relief drops', year: 2008 },
    { id: 18, title: 'Hewitt', submitter: 'MXD', status_name: 'Leader TabTussin 400', year: 2007 },
    { id: 19, title: 'Selina', submitter: 'TCB', status_name: 'Valacyclovir Hydrochloride', year: 2006 },
    { id: 20, title: 'Nanine', submitter: 'NPL', status_name: 'Allergy and Congestion Relief', year: 2000 },
    { id: 21, title: 'Iolande', submitter: 'CVH', status_name: 'Night Time Cherry', year: 2004 },
    { id: 22, title: 'Enid', submitter: 'EGA', status_name: 'Amlodipine Besylate', year: 2001 },
    { id: 23, title: 'Myca', submitter: 'GYA', status_name: 'OPANA', year: 1987 },
    { id: 24, title: 'Marley', submitter: 'HLN', status_name: 'STUDIO FIX FLUID SPF 15 BROAD SPECTRUM', year: 2006 },
    { id: 25, title: 'Waldon', submitter: 'JOL', status_name: 'Childrens Silfedrine', year: 2007 },
    { id: 26, title: 'Twyla', submitter: 'MRK', status_name: 'venlafaxine', year: 2001 },
    { id: 27, title: 'Orv', submitter: 'SXW', status_name: 'METOPROLOL SUCCINATE', year: 2008 },
    { id: 28, title: 'Gina', submitter: 'LOY', status_name: 'Stay Awake', year: 1985 },
    { id: 29, title: 'Catrina', submitter: 'BSE', status_name: 'Curvularia', year: 2008 },
    { id: 30, title: 'Peyton', submitter: 'WPU', status_name: 'Lorazepam', year: 1993 },
    { id: 31, title: 'Harriott', submitter: 'FEL', status_name: 'Senna-S', year: 1993 },
    { id: 32, title: 'Sigismundo', submitter: 'CRK', status_name: 'Sumatriptan Succinate', year: 1999 },
    { id: 33, title: 'Randall', submitter: 'KYX', status_name: 'Nite Time Cold Head Congestion', year: 2008 },
    { id: 34, title: 'Fee', submitter: 'MXL', status_name: 'PURIXAN', year: 2005 },
    { id: 35, title: 'Farrand', submitter: 'BSV', status_name: 'La Roche-Posay Laboratoire Pharmacetique HydraPhase UV Eyes', year: 1997 },
    { id: 36, title: 'Hirsch', submitter: 'TKD', status_name: 'Cephalexin', year: 2008 },
    { id: 37, title: 'Pearce', submitter: 'ADM', status_name: 'METFORMIN HYDROCHLORIDE', year: 1973 },
    { id: 38, title: 'Jaquenetta', submitter: 'OGS', status_name: 'Lamotrigine', year: 1987 },
    { id: 39, title: 'Marcos', submitter: 'YKY', status_name: 'The Medicine Shoppe Chest Congestion Relief', year: 2002 },
    { id: 40, title: 'Tori', submitter: 'LYO', status_name: 'AcneVir', year: 2004 },
    { id: 41, title: 'Godfree', submitter: 'WDN', status_name: 'Nasal Decongestant', year: 1995 },
    { id: 42, title: 'Kaja', submitter: 'BPX', status_name: 'enMotion', year: 2003 },
    { id: 43, title: 'Karylin', submitter: 'SRS', status_name: 'Carisoprodol', year: 2007 },
    { id: 44, title: 'Alysia', submitter: 'AGP', status_name: 'Allergy', year: 1997 },
    { id: 45, title: 'Adams', submitter: 'SKR', status_name: 'SHISEIDO RADIANT LIFTING FOUNDATION', year: 1995 },
    { id: 46, title: 'Carolann', submitter: 'MGQ', status_name: 'Pier 1 Imports Coconut Breeze Anti-bacterial Hand Wash', year: 1993 },
    { id: 47, title: 'Floria', submitter: 'AQG', status_name: 'Sulfamethoxazole and Trimethoprim', year: 1999 },
    { id: 48, title: 'Kittie', submitter: 'AXJ', status_name: 'CAREALL Musle and Joint', year: 2012 },
    { id: 49, title: 'Maryellen', submitter: 'DOO', status_name: 'Sterile Vancomycin Hydrochloride', year: 2004 },
    { id: 50, title: 'Rosalia', submitter: 'PGZ', status_name: 'Clopidogrel', year: 2001 },
    { id: 51, title: 'Ringo', submitter: 'YPO', status_name: 'Cetirizine', year: 2001 },
    { id: 52, title: 'Cathleen', submitter: 'MZE', status_name: 'Carp', year: 2001 },
    { id: 53, title: 'Misha', submitter: 'MOA', status_name: 'Levetiracetam', year: 2005 },
    { id: 54, title: 'Lock', submitter: 'PCD', status_name: 'Zep Provisions Pot and Pan Premium', year: 1993 },
    { id: 55, title: 'Eal', submitter: 'YTM', status_name: 'Neupro', year: 2013 },
    { id: 56, title: 'Karine', submitter: 'GOU', status_name: 'Norpace', year: 2002 },
    { id: 57, title: 'Celeste', submitter: 'TKQ', status_name: 'Mirtazapine', year: 2007 },
    { id: 58, title: 'Auberta', submitter: 'RNA', status_name: 'Anxiety', year: 2009 },
    { id: 59, title: 'Corey', submitter: 'BBZ', status_name: 'Sleep aid', year: 1993 },
    { id: 60, title: 'Ferguson', submitter: 'LSO', status_name: 'ShopRite Arthritis Pain', year: 1993 },
    { id: 61, title: 'Ellynn', submitter: 'GSQ', status_name: 'Valsartan and Hydrochlorothiazide', year: 2004 },
    { id: 62, title: 'Nathalie', submitter: 'IDF', status_name: 'Aspirin', year: 2002 },
    { id: 63, title: 'Alard', submitter: 'YHA', status_name: 'California Scrub Oak Pollen', year: 2004 },
    { id: 64, title: 'Lorry', submitter: 'CEF', status_name: 'Novana Moisturizing', year: 2008 },
    { id: 65, title: 'Alia', submitter: 'JIQ', status_name: 'Dextrose', year: 1991 },
    { id: 66, title: 'Rosie', submitter: 'LPM', status_name: 'Nicardipine Hydrochloride', year: 1987 },
    { id: 67, title: 'Jacob', submitter: 'KFA', status_name: 'Cardizem LA', year: 1998 },
    { id: 68, title: 'Aymer', submitter: 'MFC', status_name: 'PAXIL', year: 1999 },
    { id: 69, title: 'Shelia', submitter: 'SGX', status_name: 'Galantamine', year: 2004 },
    { id: 70, title: 'Melesa', submitter: 'IZA', status_name: 'Triaminic', year: 2008 },
    { id: 71, title: 'Artemis', submitter: 'TML', status_name: 'Dipyridamole', year: 2012 },
    { id: 72, title: 'Terencio', submitter: 'GBG', status_name: 'Degree', year: 1994 },
    { id: 73, title: 'Rhetta', submitter: 'NSH', status_name: 'Droperidol', year: 1990 },
    { id: 74, title: 'Torry', submitter: 'SDJ', status_name: 'Duloxetine', year: 1994 },
    { id: 75, title: 'Genvieve', submitter: 'KWO', status_name: 'LBEL', year: 2011 },
    { id: 76, title: 'Shell', submitter: '0', status_name: 'AMOREPACIFIC', year: 2000 },
    { id: 77, title: 'Esdras', submitter: 'YIO', status_name: 'Neutrogena Healthy Skin Glow Sheers Illuminating Tinted Moisturizer - Medium to Tan 40', year: 2003 },
    { id: 78, title: 'Tressa', submitter: 'QCN', status_name: 'Isosorbide Dinitrate', year: 2012 },
    { id: 79, title: 'Melesa', submitter: 'YBJ', status_name: 'OCLIPSE Sunscreen plus Primer Broad-Spectrum SPF 30 UVA/UVB Protection', year: 2008 },
    { id: 80, title: 'Nicoline', submitter: 'MLS', status_name: 'HealthMart Mucus Relief FM', year: 2008 },
    { id: 81, title: 'Jamill', submitter: 'MYZ', status_name: 'Glipizide and Metformin HCl', year: 1992 },
    { id: 82, title: 'Husain', submitter: 'BCA', status_name: 'Oxycodone and Acetaminophen', year: 2007 },
    { id: 83, title: 'Suzann', submitter: 'KSZ', status_name: 'Pollens - Grasses, Bahia Grass Paspalum notatum', year: 1999 },
    { id: 84, title: 'Clay', submitter: 'BQI', status_name: 'Metformin Hydrochloride', year: 2000 },
    { id: 85, title: 'Muffin', submitter: 'KEW', status_name: 'Viscum Salicis', year: 2005 },
    { id: 86, title: 'Waylin', submitter: 'SGV', status_name: 'smart sense nasal', year: 2008 },
    { id: 87, title: 'Lusa', submitter: 'SJT', status_name: 'Potassium Chloride', year: 2000 },
    { id: 88, title: 'Claudine', submitter: 'TPG', status_name: 'gentle laxative for women', year: 2001 },
    { id: 89, title: 'Lydia', submitter: 'RNB', status_name: 'Maple Leaf Sycamore', year: 1999 },
    { id: 90, title: 'Nikkie', submitter: 'PDK', status_name: 'Halls', year: 2010 },
    { id: 91, title: 'Dewitt', submitter: 'VQS', status_name: 'Adult Low strength Aspirin', year: 2002 },
    { id: 92, title: 'Shauna', submitter: 'PGM', status_name: 'Tretinoin', year: 2008 },
    { id: 93, title: 'Una', submitter: 'CUK', status_name: 'FOLIC ACID', year: 1995 },
    { id: 94, title: 'Farleigh', submitter: 'UHE', status_name: 'White Faced Hornet hymenoptera venom Venomil Maintenance', year: 1996 },
    { id: 95, title: 'Honor', submitter: 'XQU', status_name: 'Solar Protection Formula SPF 65', year: 2006 },
    { id: 96, title: 'Ephrayim', submitter: 'YHD', status_name: 'COLDS RUNNY NOSE', year: 1997 },
    { id: 97, title: 'Nealon', submitter: 'LLN', status_name: 'RUNNY NOSE', year: 2009 },
    { id: 98, title: 'Joline', submitter: 'BIO', status_name: 'Topicort', year: 1995 },
    { id: 99, title: 'Shara', submitter: 'YQC', status_name: 'Fluoxetine', year: 2002 },
    { id: 100, title: 'Guillema', submitter: 'OKB', status_name: 'Nighty Nite', year: 1966 }
  ];
  constructor() {}
}
