import { mountComponent } from '../../../../cypress/support/ct-utils';
import { PrWordCounterComponent } from './pr-word-counter.component';

/**
 * CONTRACT tests for `app-pr-word-counter`.
 *
 * Source of truth
 * ---------------
 * `master` — the component is BYTE-IDENTICAL there
 * (`git diff master -- src/app/custom-fields/pr-word-counter/*` -> empty), so the behaviour
 * asserted below is `master`'s behaviour by construction.
 *
 * Consumers (2): `pr-input` and `pr-textarea` render it under the control whenever the field
 * declares a `maxWords`, feeding it a live count:
 *
 *   <app-pr-word-counter [wordCount]="wordCount()" [maxWords]="maxWords()"
 *                        [autogenerate]="autogenerate()"></app-pr-word-counter>
 *
 * The counter is the visual half of a MANDATORY rule: `pr-input` also feeds the same comparison
 * into `app-field-card [hasError]`, which is what turns the field red and (via the card state)
 * tells the submitter the field is not acceptable. So the exact position of the threshold is
 * the contract — off by one here means fields are rejected, or accepted, one word early.
 *
 * Threshold semantics, read off the template: `invalid` when `wordCount > maxWords`.
 * Therefore `wordCount === maxWords` is VALID — the limit is inclusive.
 *
 * `mountComponent` (not a template tag): `PrWordCounterComponent` is declared but NOT exported
 * from `CustomFieldsModule`, so a `<app-pr-word-counter>` tag in a host template silently
 * renders nothing.
 */

const mount = (props: Record<string, unknown>) => mountComponent(PrWordCounterComponent, { componentProperties: props });

describe('PrWordCounterComponent — contract', () => {
  describe('reporting the count', () => {
    it('[contract] states the limit', () => {
      mount({ wordCount: 3, maxWords: 10 });
      cy.get('.word_counter').should('contain.text', 'Max 10 words');
    });

    it('[contract] reports the current count against the limit', () => {
      mount({ wordCount: 3, maxWords: 10 });
      cy.get('.limitBreaker').should('have.text', '3');
      cy.get('.word_counter').should('contain.text', '/ 10');
    });

    it('[contract] reports 0 for an empty field rather than blank', () => {
      mount({ wordCount: 0, maxWords: 10 });
      cy.get('.limitBreaker').should('have.text', '0');
      cy.get('.word_counter').should('not.have.class', 'invalid');
    });
  });

  describe('the threshold (the limit is inclusive)', () => {
    it('[contract] one word below the limit is valid', () => {
      mount({ wordCount: 9, maxWords: 10, autogenerate: false });
      cy.get('.word_counter').should('not.have.class', 'invalid');
      cy.get('.limitBreaker').should('not.have.class', 'invalid');
    });

    it('[contract] EXACTLY at the limit is still valid', () => {
      mount({ wordCount: 10, maxWords: 10, autogenerate: false });
      cy.get('.word_counter').should('not.have.class', 'invalid');
      cy.get('.limitBreaker').should('not.have.class', 'invalid');
    });

    it('[contract] one word over the limit is invalid', () => {
      mount({ wordCount: 11, maxWords: 10, autogenerate: false });
      cy.get('.word_counter').should('have.class', 'invalid');
      cy.get('.limitBreaker').should('have.class', 'invalid');
    });

    it('[contract] well over the limit is invalid', () => {
      mount({ wordCount: 250, maxWords: 10, autogenerate: false });
      cy.get('.word_counter').should('have.class', 'invalid');
      cy.get('.limitBreaker').should('have.class', 'invalid');
      cy.get('.limitBreaker').should('have.text', '250');
    });

    it('[contract] flags invalid visually — the over-limit count is not styled like a valid one', () => {
      mount({ wordCount: 10, maxWords: 10, autogenerate: false });
      cy.get('.limitBreaker')
        .then($el => window.getComputedStyle($el[0]).color)
        .then(validColor => {
          mount({ wordCount: 11, maxWords: 10, autogenerate: false });
          cy.get('.limitBreaker').then($el => {
            expect(window.getComputedStyle($el[0]).color, 'over-limit is visually distinct').to.not.equal(String(validColor));
          });
        });
    });
  });

  describe('autogenerated text is warned about, not rejected', () => {
    it('[contract] over the limit with autogenerate on warns instead of invalidating', () => {
      mount({ wordCount: 11, maxWords: 10, autogenerate: true });
      cy.get('.word_counter').should('have.class', 'warning');
      cy.get('.limitBreaker').should('have.class', 'warning').and('not.have.class', 'invalid');
    });

    it('[contract] at the limit with autogenerate on is neither warning nor invalid', () => {
      mount({ wordCount: 10, maxWords: 10, autogenerate: true });
      cy.get('.word_counter').should('not.have.class', 'warning').and('not.have.class', 'invalid');
    });
  });

  describe('degenerate inputs (the parent computes these, so they must never blow up)', () => {
    it('[contract] survives an undefined count without flagging an error', () => {
      mount({ wordCount: undefined, maxWords: 10 });
      cy.get('.word_counter').should('exist').and('not.have.class', 'invalid');
    });

    it('[contract] survives a null count without flagging an error', () => {
      mount({ wordCount: null, maxWords: 10 });
      cy.get('.word_counter').should('exist').and('not.have.class', 'invalid');
    });

    it('[contract] treats a zero limit as "any word is over"', () => {
      mount({ wordCount: 1, maxWords: 0, autogenerate: false });
      cy.get('.word_counter').should('contain.text', 'Max 0 words').and('have.class', 'invalid');
    });
  });
});
