import { ComponentFixture, TestBed } from '@angular/core/testing';

import { PrWordCounterComponent } from './pr-word-counter.component';

describe('PrWordCounterComponent', () => {
  let component: PrWordCounterComponent;
  let fixture: ComponentFixture<PrWordCounterComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [PrWordCounterComponent]
    }).compileComponents();

    fixture = TestBed.createComponent(PrWordCounterComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  /*
   * 🛑 `setInput`, no asignación directa. La app corre zoneless: escribir el campo a mano deja la
   * vista SIN marcar como sucia, así que el siguiente `detectChanges()` no la refresca pero sí
   * corre `checkNoChanges` — y ahí salta un NG0100 que no es del componente, es del test.
   */
  const render = (wordCount: any, maxWords: number, autogenerate = false) => {
    fixture.componentRef.setInput('wordCount', wordCount);
    fixture.componentRef.setInput('maxWords', maxWords);
    fixture.componentRef.setInput('autogenerate', autogenerate);
    fixture.detectChanges();
  };

  const el = (sel: string) => fixture.nativeElement.querySelector(sel) as HTMLElement;
  const root = () => el('.word_counter');
  const ring = () => el('.wc_ring_value') as unknown as SVGCircleElement;

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  /*
   * Lo que NO cambió con la propuesta 04. `pr-input` y `pr-textarea` leen `.limitBreaker` y las
   * clases `invalid` / `warning`, y la misma comparación alimenta `[hasError]` de la tarjeta de
   * campo: el rediseño toca la presentación, nunca el contrato.
   */
  describe('el contrato que heredan pr-input y pr-textarea', () => {
    it('keeps the figure alone inside .limitBreaker', () => {
      render(3, 10);
      expect(el('.limitBreaker').textContent).toBe('3');
      expect(root().textContent).toContain('/ 10');
    });

    it('reports 0 for an empty field rather than blank', () => {
      render(0, 10);
      expect(el('.limitBreaker').textContent).toBe('0');
      expect(root().classList).not.toContain('invalid');
    });

    it('treats the limit as inclusive — exactly at it is still valid', () => {
      render(10, 10);
      expect(root().classList).not.toContain('invalid');

      render(11, 10);
      expect(root().classList).toContain('invalid');
      expect(el('.limitBreaker').classList).toContain('invalid');
    });

    it('warns instead of invalidating when the text was autogenerated', () => {
      render(11, 10, true);
      expect(root().classList).toContain('warning');
      expect(root().classList).not.toContain('invalid');
    });
  });

  /*
   * El aro es lo que la propuesta 04 añade: decir cuánto QUEDA sin obligar a comparar dos cifras.
   * jsdom no pinta, así que se mide el `stroke-dashoffset` — que es exactamente el número del que
   * depende el dibujo. Offset = perímetro → vacío; offset = 0 → lleno.
   */
  describe('el aro', () => {
    const offset = () => Number(ring().getAttribute('stroke-dashoffset'));
    const full = () => Number(ring().getAttribute('stroke-dasharray'));

    it('is empty on an empty field and full at the limit', () => {
      render(0, 10);
      expect(offset()).toBeCloseTo(full(), 5);

      render(10, 10);
      expect(offset()).toBeCloseTo(0, 5);
    });

    it('fills proportionally in between', () => {
      render(5, 10);
      expect(offset()).toBeCloseTo(full() / 2, 5);
    });

    it('never overfills past the limit', () => {
      render(250, 10);
      expect(offset()).toBeCloseTo(0, 5);
      expect(offset()).toBeGreaterThanOrEqual(0);
    });

    /*
     * `maxWords = 0` llega de verdad: el padre lo calcula. Dividir por él daría `Infinity`, el
     * navegador descartaría el atributo y el aro quedaría pintado ENTERO con el campo vacío —
     * justo al revés de lo que pasa.
     */
    it('survives a zero limit without emitting a non-finite offset', () => {
      render(1, 0);
      expect(Number.isFinite(offset())).toBe(true);
      expect(offset()).toBeCloseTo(0, 5);

      render(0, 0);
      expect(Number.isFinite(offset())).toBe(true);
      expect(offset()).toBeCloseTo(full(), 5);
    });

    it('survives an undefined count without flagging an error', () => {
      render(undefined, 10);
      expect(Number.isFinite(offset())).toBe(true);
      expect(root().classList).not.toContain('invalid');
      expect(el('.limitBreaker').textContent).toBe('0');
    });
  });

  /*
   * El aviso ANTES del accidente — lo que el contador plano nunca dio: solo cambiaba de color
   * cuando ya te habías pasado, que es cuando ya no sirve de nada.
   */
  describe('el aviso de cercanía', () => {
    it('stays quiet while the field is comfortable', () => {
      render(20, 30);
      expect(root().classList).not.toContain('near-limit');
    });

    it('warns from 85% of the budget on', () => {
      render(26, 30);
      expect(root().classList).toContain('near-limit');
    });

    it('is not a near-limit warning once it is actually over', () => {
      render(31, 30);
      expect(root().classList).toContain('invalid');
      expect(root().classList).not.toContain('near-limit');
    });

    it('never warns on an empty field, whatever the budget', () => {
      render(0, 1);
      expect(root().classList).not.toContain('near-limit');
    });
  });

  /* Un aro y dos cifras son tres formas de lo mismo para quien no ve la pantalla. */
  describe('lo que se anuncia', () => {
    it('reads as one sentence, and says it is over instead of relying on colour', () => {
      render(3, 10);
      expect(root().getAttribute('role')).toBe('img');
      expect(root().getAttribute('aria-label')).toBe('3 of 10 words');
      expect(el('.wc_ring').getAttribute('aria-hidden')).toBe('true');

      render(11, 10);
      expect(root().getAttribute('aria-label')).toBe('11 of 10 words — over the limit');
    });
  });
});
