import { MigrationInterface, QueryRunner } from "typeorm";

export class resultsInnovationPackage1678139273093 implements MigrationInterface {
    name = 'resultsInnovationPackage1678139273093'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`results_innovation_package_countries\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`result_innovation_package_region_id\` bigint NOT NULL AUTO_INCREMENT, \`result_innovation_package_id\` bigint NOT NULL, \`country_id\` int NOT NULL, PRIMARY KEY (\`result_innovation_package_region_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`non_pooled_innovation_package_project\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`non_pooled_package_project_id\` bigint NOT NULL AUTO_INCREMENT, \`grant_title\` text NOT NULL, \`center_grant_id\` text NOT NULL, \`results_package_id\` bigint NOT NULL, \`lead_center_id\` varchar(15) CHARACTER SET "utf8" COLLATE "utf8_unicode_ci" NULL, \`funder_institution_id\` int NOT NULL, PRIMARY KEY (\`non_pooled_package_project_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`results_innovation_package_center\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`results_package_center_id\` bigint NOT NULL AUTO_INCREMENT, \`is_primary\` tinyint NULL, \`center_id\` varchar(15) CHARACTER SET "utf8" COLLATE "utf8_unicode_ci" NULL, \`result_package_id\` bigint NOT NULL, PRIMARY KEY (\`results_package_center_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`results_innovation_package_region\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`result_innovation_package_region_id\` bigint NOT NULL AUTO_INCREMENT, \`result_innovation_package_id\` bigint NOT NULL, \`region_id\` int NOT NULL, PRIMARY KEY (\`result_innovation_package_region_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`results_innovation_package_by_initiative\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`results_package_by_initiative_id\` bigint NOT NULL AUTO_INCREMENT, \`initiative_id\` int NOT NULL, \`initiative_role_id\` bigint NOT NULL, \`results_package_id\` bigint NOT NULL, PRIMARY KEY (\`results_package_by_initiative_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`results_innovation_package_toc_result\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`results_package_toc_result_id\` bigint NOT NULL AUTO_INCREMENT, \`toc_result_id\` int NOT NULL, \`results_package_id\` bigint NOT NULL, \`planned_result_packages\` tinyint NOT NULL, PRIMARY KEY (\`results_package_toc_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`results_innovation_package\` (\`is_active\` tinyint NOT NULL DEFAULT 1, \`version_id\` bigint NOT NULL, \`create_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_update_date\` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`create_by\` bigint NULL, \`last_update_by\` bigint NULL, \`result_innovation_package_id\` bigint NOT NULL AUTO_INCREMENT, \`result_id\` bigint NOT NULL, \`initiative_id\` int NOT NULL, \`geo_scope_id\` int NOT NULL, \`title\` text NOT NULL, \`description\` text NULL, \`gender_tag_level_id\` bigint NOT NULL, \`climate_tag_level_id\` bigint NOT NULL, \`is_krs\` tinyint NULL, PRIMARY KEY (\`result_innovation_package_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_countries\` ADD CONSTRAINT \`FK_e68f6d8238a5393a5020f9dde8d\` FOREIGN KEY (\`result_innovation_package_id\`) REFERENCES \`results_innovation_package\`(\`result_innovation_package_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_countries\` ADD CONSTRAINT \`FK_1a2082b6a2a6f71b73a30c56455\` FOREIGN KEY (\`country_id\`) REFERENCES \`clarisa_countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_countries\` ADD CONSTRAINT \`FK_cfd4854f5e369033053e3a7dcab\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` ADD CONSTRAINT \`FK_84acccf33e414b2aff41d3c7e3b\` FOREIGN KEY (\`results_package_id\`) REFERENCES \`results_innovation_package\`(\`result_innovation_package_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` ADD CONSTRAINT \`FK_605b138df8031b95708d80c51ca\` FOREIGN KEY (\`lead_center_id\`) REFERENCES \`clarisa_center\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` ADD CONSTRAINT \`FK_5b616048b0fa95f545938cb1757\` FOREIGN KEY (\`funder_institution_id\`) REFERENCES \`clarisa_institutions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` ADD CONSTRAINT \`FK_5a83e7a4bdd41f376db8d38f7b2\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_center\` ADD CONSTRAINT \`FK_7fab5f14b2b91e0969892f4dfcd\` FOREIGN KEY (\`center_id\`) REFERENCES \`clarisa_center\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_center\` ADD CONSTRAINT \`FK_075d2fe7f43b1fe2f6ca76a479e\` FOREIGN KEY (\`result_package_id\`) REFERENCES \`results_innovation_package\`(\`result_innovation_package_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_center\` ADD CONSTRAINT \`FK_9636aee4523bea12c102e92be36\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_region\` ADD CONSTRAINT \`FK_928fcca9b51c425cfd0f6683f25\` FOREIGN KEY (\`result_innovation_package_id\`) REFERENCES \`results_innovation_package\`(\`result_innovation_package_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_region\` ADD CONSTRAINT \`FK_884159bbfad72502ab772b85910\` FOREIGN KEY (\`region_id\`) REFERENCES \`clarisa_regions\`(\`um49Code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_region\` ADD CONSTRAINT \`FK_f10b7b7d769a6a6de31b3bbaab5\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` ADD CONSTRAINT \`FK_4e1b5fe057759ac28b2f81a6469\` FOREIGN KEY (\`results_package_id\`) REFERENCES \`results_innovation_package\`(\`result_innovation_package_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` ADD CONSTRAINT \`FK_0dee52af9ae7f78f299add0a36b\` FOREIGN KEY (\`initiative_role_id\`) REFERENCES \`initiative_roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` ADD CONSTRAINT \`FK_f68560c31995a8e76be1a00115d\` FOREIGN KEY (\`initiative_id\`) REFERENCES \`clarisa_initiatives\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` ADD CONSTRAINT \`FK_52a4633b59c81a72564cfaa1a93\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_toc_result\` ADD CONSTRAINT \`FK_ecb4b0e65de824646ce5aa80cb6\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_toc_result\` ADD CONSTRAINT \`FK_5f1f5fdc85269e7e6a7f3433ebe\` FOREIGN KEY (\`results_package_id\`) REFERENCES \`results_innovation_package\`(\`result_innovation_package_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_toc_result\` ADD CONSTRAINT \`FK_f41ff6ec294e044f2c2fa84635d\` FOREIGN KEY (\`toc_result_id\`) REFERENCES \`toc_result\`(\`toc_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` ADD CONSTRAINT \`FK_27f77efe85b609a24790b5955b6\` FOREIGN KEY (\`result_id\`) REFERENCES \`result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` ADD CONSTRAINT \`FK_29c106f0dfc0b75388aa5417bf5\` FOREIGN KEY (\`initiative_id\`) REFERENCES \`clarisa_initiatives\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` ADD CONSTRAINT \`FK_021527efef0b8b82597b28f755f\` FOREIGN KEY (\`geo_scope_id\`) REFERENCES \`clarisa_geographic_scope\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` ADD CONSTRAINT \`FK_e2b14a6161b1ab6a0011ec6a94f\` FOREIGN KEY (\`gender_tag_level_id\`) REFERENCES \`gender_tag_level\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` ADD CONSTRAINT \`FK_c109ccf987d75de0559ce13f100\` FOREIGN KEY (\`climate_tag_level_id\`) REFERENCES \`gender_tag_level\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` ADD CONSTRAINT \`FK_ccf2bc76e4aeaea6da7033322a2\` FOREIGN KEY (\`version_id\`) REFERENCES \`version\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` DROP FOREIGN KEY \`FK_ccf2bc76e4aeaea6da7033322a2\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` DROP FOREIGN KEY \`FK_c109ccf987d75de0559ce13f100\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` DROP FOREIGN KEY \`FK_e2b14a6161b1ab6a0011ec6a94f\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` DROP FOREIGN KEY \`FK_021527efef0b8b82597b28f755f\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` DROP FOREIGN KEY \`FK_29c106f0dfc0b75388aa5417bf5\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package\` DROP FOREIGN KEY \`FK_27f77efe85b609a24790b5955b6\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_toc_result\` DROP FOREIGN KEY \`FK_f41ff6ec294e044f2c2fa84635d\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_toc_result\` DROP FOREIGN KEY \`FK_5f1f5fdc85269e7e6a7f3433ebe\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_toc_result\` DROP FOREIGN KEY \`FK_ecb4b0e65de824646ce5aa80cb6\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` DROP FOREIGN KEY \`FK_52a4633b59c81a72564cfaa1a93\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` DROP FOREIGN KEY \`FK_f68560c31995a8e76be1a00115d\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` DROP FOREIGN KEY \`FK_0dee52af9ae7f78f299add0a36b\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_by_initiative\` DROP FOREIGN KEY \`FK_4e1b5fe057759ac28b2f81a6469\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_region\` DROP FOREIGN KEY \`FK_f10b7b7d769a6a6de31b3bbaab5\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_region\` DROP FOREIGN KEY \`FK_884159bbfad72502ab772b85910\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_region\` DROP FOREIGN KEY \`FK_928fcca9b51c425cfd0f6683f25\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_center\` DROP FOREIGN KEY \`FK_9636aee4523bea12c102e92be36\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_center\` DROP FOREIGN KEY \`FK_075d2fe7f43b1fe2f6ca76a479e\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_center\` DROP FOREIGN KEY \`FK_7fab5f14b2b91e0969892f4dfcd\``);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` DROP FOREIGN KEY \`FK_5a83e7a4bdd41f376db8d38f7b2\``);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` DROP FOREIGN KEY \`FK_5b616048b0fa95f545938cb1757\``);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` DROP FOREIGN KEY \`FK_605b138df8031b95708d80c51ca\``);
        await queryRunner.query(`ALTER TABLE \`non_pooled_innovation_package_project\` DROP FOREIGN KEY \`FK_84acccf33e414b2aff41d3c7e3b\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_countries\` DROP FOREIGN KEY \`FK_cfd4854f5e369033053e3a7dcab\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_countries\` DROP FOREIGN KEY \`FK_1a2082b6a2a6f71b73a30c56455\``);
        await queryRunner.query(`ALTER TABLE \`results_innovation_package_countries\` DROP FOREIGN KEY \`FK_e68f6d8238a5393a5020f9dde8d\``);
        await queryRunner.query(`DROP TABLE \`results_innovation_package\``);
        await queryRunner.query(`DROP TABLE \`results_innovation_package_toc_result\``);
        await queryRunner.query(`DROP TABLE \`results_innovation_package_by_initiative\``);
        await queryRunner.query(`DROP TABLE \`results_innovation_package_region\``);
        await queryRunner.query(`DROP TABLE \`results_innovation_package_center\``);
        await queryRunner.query(`DROP TABLE \`non_pooled_innovation_package_project\``);
        await queryRunner.query(`DROP TABLE \`results_innovation_package_countries\``);
    }

}
