name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download environment files from AWS Secrets Manager
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          mkdir -p onecgiar-pr-client/src/environments

          # Obtener el secreto
          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id dev/app/frontend/alliance/reportingtool \
            --query SecretString \
            --output text)

          # DEBUG: Mostrar el secreto en logs (solo para pruebas)
          echo "===== Secret descargado de AWS Secrets Manager ====="
          echo "$SECRET"
          echo "===================================================="

          # Guardar como archivo TypeScript válido
          echo "export const environment = $SECRET;" > onecgiar-pr-client/src/environments/environment.ts

          # Duplicar para producción
          cp onecgiar-pr-client/src/environments/environment.ts \
            onecgiar-pr-client/src/environments/environment.prod.ts

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: onecgiar-pr-client
          start: npm start
          wait-on: "http://localhost:4200"
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_TEST_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
