/**
 * Admin › All P/As and Centers — user-facing copy (R37). P2-3858 (INC-163934-2, Nicoleta 29-Sep-2026):
 * one page with the Overview numbers of every Program/Accelerator and every CGIAR Center.
 */
export const ADMIN_ENTITIES_OVERVIEW_COPY = {
  title: 'All P/As and Centers',
  subtitle: 'Reporting status of every Program/Accelerator and every CGIAR Center on one page — the same numbers each Overview shows.',
  phaseLabel: 'Phase',
  noPhase: 'No open reporting phase',
  programsTitle: 'Programs and Accelerators',
  programsHint: 'W1/W2 results, as on each Program Overview.',
  centersTitle: 'CGIAR Centers',
  centersHint: 'W3/Bilateral results, as on each Center Overview.',
  nameColumn: 'Name',
  totalColumn: 'Total',
  totalRow: 'All',
  openOverview: (name: string): string => `Open the ${name} Overview`,
  loadError: 'Could not load.',
  retry: 'Retry',
  programsError: 'The Programs could not be loaded.',
  centersError: 'The Centers list could not be loaded.',
  partialTotal: 'Some rows could not be loaded, so the total leaves them out.',
  empty: 'Nothing to show.',
  // Rework 5-Oct-2026 — chart view in the Portfolio overview's visual language (Cami + Ángel).
  eyebrow: 'Admin module',
  viewPrograms: 'Programs & Accelerators',
  viewCenters: 'CGIAR Centers',
  kpiTotal: 'Total results',
  kpiTotalBreakdown: (w1w2: number, bilateral: number): string => `${w1w2} W1/W2 · ${bilateral} W3/Bilateral`,
  kpiW1w2: 'W1/W2 results',
  kpiW1w2Chip: (percent: number): string => `${percent}% submitted`,
  kpiW1w2Hint: 'Across Programs & Accelerators',
  kpiBilateral: 'W3/Bilateral results',
  kpiBilateralChip: (percent: number): string => `${percent}% approved`,
  kpiBilateralHint: 'Across CGIAR Centers',
  kpiProgramsReporting: 'P/As reporting',
  kpiCentersReporting: 'Centers reporting',
  kpiReportingHint: 'with at least one result',
  resultsWord: 'results',
  statusTitle: 'Reporting status',
  statusProgramsHint: 'W1/W2 results of every Program/Accelerator in this phase.',
  statusCentersHint: 'W3/Bilateral results of every CGIAR Center in this phase.',
  activeFilter: 'Active filter:',
  viewInResultsCenter: 'View in Results Center',
  clearFilter: 'Clear filter',
  rankingProgramsTitle: 'Programs & Accelerators ranking',
  rankingCentersTitle: 'CGIAR Centers ranking',
  rankingHint: 'Results per entity, split by status. Click a status to rank by it.',
  modeHorizontal: 'Horizontal Bar',
  modeVertical: 'Vertical Bar',
  modeHeatmap: 'Heatmap',
  detailProgramsTitle: 'Progress by Program/Accelerator',
  detailCentersTitle: 'Progress by Center',
  detailHint: 'The same numbers each Overview shows. Click a header to sort, a name to open its Overview.',
  tableView: 'Table View',
  chartView: 'Chart View',
  searchPrograms: 'Search program…',
  searchCenters: 'Search center…',
  clearSearch: 'Clear search',
  shownCount: (shown: number, total: number): string => `${shown} of ${total}`,
  centersStillLoading: 'Some Centers are still loading; figures update as they arrive.'
} as const;
